baseURL = "https://mipmip.github.io/quiqr-lightbi-template/"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Lightbi"
theme = "Lightbi"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsCodefencesGuessSyntax = true
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6.0
summaryLength = "30"

[Params]
selfHosted = true
mainSections = [
  "post",
  "posts"
]
dateFormat = "02 January 2006"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = false
authorInfo = "She was born to be free, let her run wild in her own way and you will never lose her."
description = "Your can add your website description here."
previewCardImagePlacement = "bottom"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[Author]
name = "Bino Kochumol Varghese"
website = "https://binovarghese.com"
email = "sample@gmail.com"
facebook = "username"
instagram = "username"
youtube = "user/username"
twitter = "username"
linkedin = "username"
github = "username"
threads = "username"
gitlab = "username"
reddit = "username"
stackoverflow = ""
snapchat = ""
spotify = "username"
paypal = "username"
telegram = "username"
mastodon = "url"
slack = ""

[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1.0

  [[menu.main]]
  name = "Notes"
  url = "/notes/"
  weight = 2.0

  [[menu.main]]
  name = "Tags"
  url = "/tags/blog/"
  weight = 3.0

  [[menu.main]]
  name = "Collections"
  url = "/collections/"
  weight = 4.0

  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 5.0
